---
title: "Frequently Asked Questions"
date: "Last Updated `r Sys.time()`"
output: html_document
---

_page in development_

# Where can I get help using R outside of class time? 

### Online
* Chico [R User Group](https://groups.google.com/forum/#!forum/chico-rug)
* UCLA IDRE

### In Person: Fall 17 office hours 
* Mon 3-4pm, Holt 155: _Robin_, Eduardo
* Tue 10-11am, Holt 155: Robin
* Tue 2-4pm, BUTTE 211 (9/19-10/17), Robin (9/19), Edward (9/26-10/17)
* Wed 3-4pm, Holt 155: _Robin_, Eduardo
* Thu 10-11am, Holt 155: Robin

_Robin_ will not be available every MW at this time, but will be there as much as possible. 


# Other

For now start here

http://datascience.csuchico.edu/resources.html

# Class Logistics
There was a survey done in Week 1 where I asked you to tell me what more you wanted to know regarding how this class is run and what is expected out of you? Here is a compilation of those responses. As more come in I will add to this list. 


### R / Programming

* I have no background in programing and I think it would be very interesting to learn.Even in my biol 350 class, Fundamentals of Ecology, R programing was mentioned. I would like to know more about how to install R. I believe I did it correctly but not all the different consoles are coming up on mine like they showed in the video.
    - **I belive you are talking about the windows in R Studio. That may be because when you first open R by itself, you do not have a script or code file open yet. You can see more about this on my software overview [[blog post]](https://norcalbiostat.netlify.com/post/software-overview/)**
* I am not familiar with R studio. Will we be able to go through codes and other problems in class together?
    - **Yes. The videos and the course notes demonstrate how to write code to accomplish a specific task. In class we will work through how the code works, then you will work with your group to apply a code concept to a new problem.**
* I want to know more about writing code in general and what R language is. 
    - **From [Wikipedia](https://en.wikipedia.org/wiki/R_(programming_language))** 
    
> R is an open source programming language and software environment for statistical computing and graphics that is supported by the R Foundation for Statistical Computing. The R language is widely used among statisticians and data miners for developing statistical software and data analysis.

* How straongly do you recommend the R bootcamp before taking or alongside this class? First and one of the only stats classes I'll be taking with my major.
    - **That R Bootcamp (MATH 130) was designed specifically as a primer for R before taking MATH 315. It is a new course, this fall is it's first official run as MATH 130. I am working with other NS departments and faculty members to advise their students to take this course prior to 315. You can be successfull taking it concurrently as well. The more exposure to R you have early on the more comfortable you will be.**
* I would like to know more about how the R Language is better suited to learning about data interpretation. I am not a programmer, so learning to draft code seems counter-productive to learning about statistical data analysis.
    - **Hopefully as we work with data in the upcoming weeks it will make more sense how this all fits together. You're just learning enough programming to analyze your data.**
* Do we need to bring our computers to class everyday? 
    - **Except for exam days, yes.**




### Assignments / grading

* There are different assignments due on the blackboard calender due date page vs the course website weekly outline. Which do we follow ?
    - **Please let me know via email any discrepencies. Items that are due to be submitted to Blackboard should have the exact same due date. There are more items listed in the weekly overview (such as reading) that do not have a corresponding submission link in Blackboard, because there is nothing to submit.**
* I would like to know about how many suggested hours will we need outside of class in order to do well. Also, will it be a big barrier if we do not have a laptop to take to class.
    - **Every student I have spoken to says that having your own laptop makes this class easier. While we do have loaner laptops for use in class, you cannot check them out. So you must bring a flash drive to save all your work and data files on.**
* My confusion always comes from the assignments are located, how to access them , and how to turn them in.
    - **Links to download assignment instructions, and RMD template files are found on the weekly overview for that day. (Not the daily grid, but the more detailed page where you can navigate to each day using the menu bar on the left).**
    - **Assignments will nearly always be uploaded to Blackboard Learn**
* I'm a bit unclear of what to expect from this class. In high school we covered things such as chi squared test and I am curious if we will be going over equations like that or if this class will simply be mainly coding.
    - **We will be talking about some equations, but we will not be doing hand calculations that you may have done in HS. Our goal is to analyze real data using tests like the $\chi^2$ test, and focusing on how to interpret the results.**
* How much time is expected to be spent practicing using R outside of class/doing homework in order to get an A?
    - **The general rule of thumb is 3 hours of workload outside of class for every 1 hour in class. This means you are expected to spend 9 hours doing work for this class. How fast you pick up on the R language will impact this time, but the assignments have been strucutred such that learning R should not dramatically increase your workload. The important thing is while you're learning R, to try to learn why something works, not just copy/paste/pray. That way you can apply it to a new problem with minimal errors.**
* Will credit still be given to those who try to code and still fail?
    - **I can't say yes here, because your ability to generate analysis results requires successful code.**
* Will i need to download any additional programs for the class
    - **The only required programs for this class are R and R Studio. Latex is highly recommended/preferred. **
How often homework is due?
    - **Approximately a week after we cover that material in class**
* I'm hoping before you let us go at the end of the the day you could tell us where everything is, which so much already on the blackboard page I get a bit lost.
    - **I will always try to give you a reminder regarding what is due and when, and do so by pointing it out explicitly on the class website using the overhead projector. I even have alarm reminders on my fitbit watch to start wrapping things up at 10 min before the class ends. You can help me remember to do this by asking me to recap what is up next before everyone leaves.**

* I want to know that the tools I need to get every assignment turned in properly are clear.
    - **So make sure you read instructions early on, and ask clarifying questions so you know exactly what to do**
   



### Exams
* will you give us cumulative exams?
    - **Yes in the sense that you can't explain a more advanced result without knowing the basics first.** 
* Because statistical analysis is computer based, how will exams be structured?
* I would like to know more about how the tests are going to be formated, computer based or paper?
    - **They will be paper exams. I will show a graph or an analysis result and ask you to explain a concept regarding that topic. I could ask you to fill in sample data. I will have a sample Exam 1 to help address this question of exam formatting.**




### Projects
* For the group work, are we also graded by our own contributions or just our work as a whole?
        - **I intend to assign the same grade to both individuals in the pair.**
* I want to know more about the "support" groups and whether one is graded as a whole (including everyone in the group) or is one graded individually and how well they participate within the group. Because I'm assuming it might be a bit hard for Dr. Donatello to be checking up on each group and who is participating and whatnot. Also if a group member isn't showing much interest in helping out the group, what should happen? Of course, ask them if they could please participate. But will we have a survey at the end of the semester that each of us can do where we rate whether our group helped equally throughout the semester.
    - **The "support" groups is the group of people you work together in class. 
    - **I have done a survey in the past that weighted the project grade based on peer review of participation. I will also do a midterm check in with all teams to assess if all parties are doing OK. Since the project is only team based now (pairs of 2), there is less room for freeloaders. If it still becomes a major problem of non-equal distribution of effort then I can intervene. But for now see the answer to the question above.**
* how many people per group project?
    - **You will work in pairs of two**
    
* Is it gonna be 10 projects with the same group or multiple different groups?
    - **The same pair of students will work on one single project the entire semester**


    
### Other
* I want to know what tactics are used the most for teaching methods? Power points? Projector?
    - **All the lecture material is formatted as HTML or PDF. Or we are working directly in R. I will talk through code/output using the overhead projector, and supplement the lecture/notes by writing on the board. Most content will come from the videos.**
* I did want to know more about how our class would be ran, as in for example if the majority of the students are stuck would you lecture in class or would we have to attend office hours to not get behind in class. 
    - **If the majority of the class is stuck on a particular problem, I will demonstrate how to solve that problem using the projector. If the class is stuck because of lack of preparation, then we will probably end class for the day and let people get caught up on their own before we move on.**

* I would like to know if there is help offered for the programs we use to do our analysis. 
* Would there be any extra help in the student service center or will it all be based on the groups you gave us.
    - **There is no formal tutoring for R on campus. I will have a peer mentor in both classes who will be there to help. I will also have a peer mentor helping me out during office hours, and monitoring the Google Group.**


    
    