
This is the landing page for <span style="color:blue">**Applied Statistical Methods 1**</span> course taught by [Dr. Robin Donatello](www.norcalbiostat.com)  in Fall 2017 (both sections). This landing page is used for posting of regular announcements and information for students of the class. 

# Announcements

### 10/6/17 - [Week 8](https://norcalbiostat.github.io/MATH315/wk08.html)

* <span style="color:red">**Office Hours**</span>: 
    - Mon, Tue, Thu 2pm in Holt 202
    - Tue, Thu 10am in Holt 155 
    - Eduardo should still be in Holt 155 MW at 3pm. 
* Computers will be used Monday & Wednesday. 
* Conducting 1 sample analyses in R. 
    - There are data and code files to prep before Monday. **Do not wait until class to do this.** 
* Upcoming Assignments
    - Research plan outline (10/8)
    - Poster prep stage 1 (10/15)
* Exam on Friday: Foundations for Inference. Course notes Ch 4-5. 

### 9/28/17 - [Week 7](https://norcalbiostat.github.io/MATH315/wk07.html)
* Week 7 notes have been posted. 
* An Error assessment assignment has been posted to [Week 6:Wed](https://norcalbiostat.github.io/MATH315/wk06.html#wednesday:_exam_1)
* The project page has been completed. Details about the poster prep assignments are linked there. 
* The bivariate graphics assignment has been posted and ready for review. 
* Blackboard learn and the schedule on this website have been cleaned up to remove old/closed assignments. 


### 9/21/17 - [Week 6](https://norcalbiostat.github.io/MATH315/wk06.html)
I have gone through the gradebook and entered in 0's for missing assignments to date. This is done to provide you a better idea of where you stand grade-wise, going into this exam. Quizzes will remain open available up until the test on the 27th. So if you got a 0 on a Problem set or Data Camp quiz you have time to make up those points. This is also a good way to study for the exam. 


* Monday: Writing your research plan. Make sure you are paying attention to the research question spreadsheet. I'm leaving feedback and questions for you there!
* Wednesday: Exam 1. The weekly overview has details on how to prepare and a sample exam. 
* Friday: Probability. If it's been a while since you've had stats class you will have to spend some significant time preparing. 

### 9/18/17 - [Week 5](https://norcalbiostat.github.io/MATH315/wk05.html)
* Recap the DM assignment template/instructions. 
* Univariate graphics assignment due this week. This is a peer reviewed assignment. Example template posted on [week 4](https://norcalbiostat.github.io/MATH315/wk04.html).
* Peer review instructions have been added to the project page. 
* Monday we will lecture on how to interpret bivariate comparisons. The rest of the week you will work on creating them. 



### 9/11/17 - [Week 4](https://norcalbiostat.github.io/MATH315/wk04.html)
* Data Management, Graphing and Research Question Sharing, Oh My!
* You should have been watching and following along with the PDS videos for about a week now. If you are not, do this ASAP or you will fall behind. Think of these as lecture, and in class as practice time. 
* You Research questions are posted on [[THIS GOOGLE SPREADSHEET]](https://docs.google.com/a/mail.csuchico.edu/spreadsheets/d/17KyM74omyRXPa322ieiU0iv-hjiO7THhAD5TVkI1qgo/edit?usp=sharing)
    - You must log in with your @mail.csuchico.edu email address to view and edit this file. 
    - I have copied your RQ's as stated in your personal codebook assignment, and demonstrated how to take the variables chosen in the codebook, and align them with specific RQ's. 
    - **I need you to help finish and/or adjust your entry!** 
    - This is your opportunity to 
        - see what others are doing
        - find out who is using the same variables as you
        - Align your RQ with actual variables in the codebook. 
* The Project information page has been started. The link to the spreadsheet above is the first piece of info there. 
    

### 9/3/17 - [Week 3](https://norcalbiostat.github.io/MATH315/wk03.html)
* Have a great three day weekend!
* We're going to be learning how to describe the distribution of data using words, summary statistics and appropriate graphics.
* This is your last chance to get all your R/R Studio bugs resolved. Next week we're hitting the coding ground hard. 
* Be sure you're watching the PDS Videos. They contain lecture material directly related to your project. 

### 8/27/17 - [Week 2](https://norcalbiostat.github.io/MATH315/wk02.html)

This week we're going to be talking about data, doing some data entry and importing data into R.
You'll start to choose specific variables to address your research questions, conduct a literature review, and learn how to properly cite your sources. 

Here are the highlights for the week. 

* Monday
    - RAT on data types (CN 2.1)
    - Practice recording raw data and creating a codebook
    - Two (2) Data camp lessons
* Wednesday
    - Getting the Add Health data into R
    - Start to choose the variables you want to analyze
* Friday
    - Conducting a literature review
    - Using proper citation styles

**Housekeeping**
* Syllabus has been updated to include office hours: MW: 3-4pm, TR: 10-11am Holt 155
    - Tuesday OH this week (8/29) are cancelled. I'm getting my braces off!!! :D  

    

### 8/20/17 - [Week 1](https://norcalbiostat.github.io/MATH315/wk01.html)

Happy Sunday and welcome to the Fall 2017 semester! 

* Super important video for you to watch on the welcome page in Blackboard Learn. Go watch this asap!
    - On the wait list? Here is a [[You Tube]](https://www.youtube.com/watch?v=cVQPU59h6OY) copy of the intro video. 
* I will be adding your emails to Data Camp shortly. You must use the link in the email to join our classroom for credit. 

Enjoy the eclipse and I'll see you soon!


