---
title: 'Analysis Poster Guidelines'
date: "Last Updated `r Sys.time()`"
output:
  html_document:
    highlight: tango
    theme: cerulean
    toc: yes
    toc_float: yes
---
# Evaluation Rubric

If you are a part of my class then rest assured your poster will be evaluated by me, and the rest of the class. [Here]() is the grading rubric that I use. 

# Structure

### Template
* Build your poster using a [powerpoint template](http://www.posterpresentations.com/html/free_poster_templates.html), not Google Slides. 
    - Do not do a trifold tabletop template. 
* Choose either a three, or four column layout. 
* Choose the correct scaling. 
* Biology Student Research Symposium [[website]](https://www.csuchico.edu/biol/research/student_research_symp.shtml) - Additional templates and guidelines included.



### Sections
1. Abstract/introduction
2. Sample characteristics
3. Analysis methods
4. Results
5. Conclusions/discussion
6. Implications
7. References


# Aestetics

### Font size
* Readable from 10 feet

### Graphics
* Not copy/paste from R, it won't scale up well. 
    - Finalize the plot, then save it to disk
    - Save the file larger rather than smaller, then manually shrink down in PPT
    - Specify height and width in inches
    
```
postscript("filename.eps", width=5, height=3) # open the graphics device.
plot(iris$Species) # your plot goes here
dev.off() # this closes the graphics device
```
    

### Tables
* Build them in Excel, or PowerPoint tables directly


### Colors
* Colors are good - but stick to a theme/pallet. 
    - Make the colors meaningful
* Use matching theme colors in graphics

# Printing
* Don't spend a fortune! (i.e. don't go to Kinko's on Mangrove and spend $90)
* Metagraphcs $50 36x48 --still pricey
* Ellis Art (downtown and on Esplanade) $30
* Staples ($65)
* Kinko's downtown, B&W $10

# Examples
Here are [a few example posters](https://norcalbiostat.github.io/peer_review/Example_Posters.html) with comments from various locations. 


