---
title: 'Project Information'
date: "Last Updated `r Sys.time()`"
output:
  html_document:
    highlight: tango
    theme: cerulean
    toc: yes
    toc_float: yes
css: css/customh5.css
---

# Helpful R code snippits

Here is a collection of helpful R [code snippits](snippits.html) for plotting, subsetting, handling missing values and so forth. Think of it as a FAQ for R code. 

# Research Questions

Each team's research questions are posted on the first two sheets of [[THIS GOOGLE SPREADSHEET]](https://docs.google.com/a/mail.csuchico.edu/spreadsheets/d/17KyM74omyRXPa322ieiU0iv-hjiO7THhAD5TVkI1qgo/edit?usp=sharing)

* You must log in with your @mail.csuchico.edu email address to view and edit this file. 
* It will be helpful to everyone if you help keep your teams entry up to date. 
* There are comments in here from me to you. Heed them. 

----

# Peer Review Rotation
* For each assignment your team is assigned to revew two other teams.
    - The peer review assignment is found on the "[Peer Review](https://docs.google.com/a/mail.csuchico.edu/spreadsheets/d/17KyM74omyRXPa322ieiU0iv-hjiO7THhAD5TVkI1qgo/edit?usp=sharing)" tab of the same Google Sheet above. 
    - The review form for each assignment is linked below that assignment. 
* All reviews are public. A link will be included to view the review responses. 
* After the review deadline has passed each team should go examine the reviews they recieved and talk with the reviewer group for clarification if necessary. 


## Univariate Graphics
* [Assignments ready for review](https://norcalbiostat.github.io/peer_review/univ_graphics.html)
* [Peer Review Form](https://goo.gl/forms/P3aDmgvWxd91L8022)
* [Review Response Spreadsheet](https://docs.google.com/spreadsheets/d/1DqUSzcmMqBvOuSgWEy61th8Y7aBVQYcsT8_aaquNpWg/edit?usp=sharing). 
    - Use column filters to more easily find your team's reviews. 
    - These are highlighted green. 

## Bivariate Graphics
* [Assignments ready for review](https://norcalbiostat.github.io/peer_review/biv_graphics.html)
* [Peer Review Form](https://goo.gl/forms/2OxIQAcFIuPYotNC2)
* [Summary of responses](https://docs.google.com/forms/d/e/1FAIpQLSdsWFU-T-UF7MKRGxh4t89uFa7TZJFB9oawVsChFwcea0Wjzg/viewanalytics). This is a diferent view from last time. You should be able to see common themes in recommendations this way.  
 
 
## Other shared completed assignments
* [Bivariate Inference](https://drive.google.com/drive/folders/0B83Z8_sNw3KPWGQxU1FsNm1DcG8?usp=sharing)   
* [Moderation](https://drive.google.com/drive/folders/0B83Z8_sNw3KPU3dsamgwOWVHVzg?usp=sharing)   
* [Regression and Confounding](https://drive.google.com/drive/folders/0B83Z8_sNw3KPcFBabzNpNHFOdFU?usp=sharing)   
* [Poster Prep Slides](https://drive.google.com/drive/folders/0B83Z8_sNw3KPUWFRdXo3WUdiNUk?usp=sharing)

----

# Poster preparation

You will organize your research in stages by building a "powerpoint" type presentation. This will help you concicely explain your research topic and findings in a way that you can more easily translate (fit) onto a poster where your sizes are constrained. 

### Instructions
* Create a Google Slides presentation directly in the Add Health Posters [Google Drive Folder](https://drive.google.com/drive/folders/0B83Z8_sNw3KPUWFRdXo3WUdiNUk?usp=sharing).
* Name it using `first_last` or `team_name` only. 
* The required contents for each slide are listed below under **Stages**
* DO NOT UPLOAD A POWER POINT FILE. There's a reason I say use Google Slides.
* At each stage drop a note in Blackboard learn under the correct assignment stating that your project is ready for review. Do not upload your project slides to Blackboard learn, they will be ignored and deleted. 


### Peer Review
* Peer review starts the date the assignment is due, with a review window of 2-5 days. 
* Use the peer rotation spreadsheet to find your assignment. 
* Use the commenting feature directly in Google Sheets to provide feedback and suggestions. 
* Use the same type of reviewing criteria, make sure you have at least 1 positive comment and 1 suggestion for improvement. 
* <span style="color:red">Once you have completed this peer review drop a note in Blackboard under the specific review assignment stating that you are done. </span> 
    - If abuse of this honor system is found (i.e. you say you have reviewed someone but there is no record of it) your team will be removed from the reviewer pool and receive 0 points for all future reviews. 

### Stages
* At each stage you should update anything you need to change, such as correctly making graphics, writing results correctly etc. 
* This includes reviewing the current set of feedback and make the appropriate corrections. 
    - Once you have addressed a particular piece of feedback mark it as "resolved" in Google Slides. 


### List of slide contents
Your presentation should be limited to approximately 16 slides. The contents of each slide are listed below. 

#### <span style="color:blue">**Stage 1**</span>
1. Title 
2. Introduction 
3. Background & lit review. 
4. Explain the research problem
5. State your Research Question. 
6. Sample characteristics: How many people are in your analysis sample, what is the % female, average (SD) age, and ethnicity breakdown.
7. Description of measures (variables) being used. Explain any recoding and/or altering that was done. 
    - This refers to changes to the data that are above and beyond setting missing codes such as 98 and 99 to `NA`. 
    - Do not use variable names. 
    - Restrict this list to only the variables you are using in your analysis. This is likely not to be more than 4-6. 
8. Univariate graphic and description of main explanatory variable. 
9. Univariate graphic and description of at least one response variable.


#### <span style="color:blue">**Stage 2**</span>
Slide 10-11: Bivariate graphics and analysis. 

Each slide should contain the following:  

1. A fully labeled and cleaned up plot demonstrating the bivariate relationship under consideration.
2. The results of an appropriate bivariate analysis. This should be a conclusion written in english, includes a confidence interval and a p-value. You also need to state the name of the test you used. 

Refer to the [Bivariate Inference](hw/Bivariate_Inference.html) assignment on how to conduct and interpret these bivariate analyses.

#### <span style="color:blue">**Stage 3**</span>

Slide 12-13:  Multivariate Analysis
Build a multivariable model to explain your outcome variable. 

* Test for moderators, and confounders
* Add other necessary covariates to controll for. 
* Assess the relationship between your explanatory and response variable after controlling for other measures. 

* Moderation:
    - If you found a moderator: Remove the bivariate graph and write up from your poster and replace with explanation of moderator and graph of significant bivariate at the 3rd variable level.
    - If you did NOT find a moderator: Include a slide stating what relationships you tested for moderation and with what variable to see if it was a moderator, explaining that it was not a moderator. No graphs needed
* Confounding: 
    - If you found a confounder: on slide with bivariate relationship that was confounded put a bullet point that explains what variable confounded the relationship and put the written results that are shown in the confounding assignment on how to write results. Make sure to explain if it helped improve prediction of response variable. 
    - If you did NOT find a confounder: Include a slide stating what relationships you tested for confounds and with what variable to see if it was a confound, explaining that it was not a moderator. Make sure to explain if it helped improve prediction of response variable. 


Slide 14. Discussion

* Here you will explain what your graphical and inferential results tell you about your topic.
* Discuss if your research hypothesis was supported, if it was not, why you think that might be
* Explain the overall story/trend/what you learned when you consider your univariate, bivariate & multivariate results about your topic.
* Compare your results to previous research results.

Slide 15. Implications

* What are the practical implications of your results?
* What future research needs to be conducted?


Slide 16. References  

* You can use smaller font to get all references on one slide.
* Use references from research plan, and any additional references gathered along the way. 
* Make sure these are correctly done in APA format.

----

# Final Posters
* During week 14 you will transfer all findings into a research poster. 
* You will present your poster to half the class during dead week (week 15)
*   - The day you are not presenting, you will be judging the other half of the class's posters. 
* Use these [poster guidelines](poster_guidelines.html) to develop your poster. 
* There will be one draft review process. 


Poster Drafts and Final posters will be linked here. 

<button data-toggle="collapse" data-target="#draft">Show/Hide Drafts for Review</button>
<div id="draft" class="collapse">

</div>

<button data-toggle="collapse" data-target="#final">Show/Hide Final Versions</button>
<div id="final" class="collapse">

</div>



