
```{r echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr);library(readxl); library(kableExtra)
options(knitr.table.format = "html", knitr.kable.NA = '') 
```

```{r echo=FALSE}
rawdat <- read_excel("schedule_315.xlsx")
cdat   <- rawdat %>% mutate(Date = format(date, "%m/%d"), 
                            Topics = topic, Notes = notes,
                            Prepare = before, Together=during,
                            HW = after, Wk=Week) %>% 
              select(Notes, Date, Topics, Prepare, Together, HW, topic, before, during, after)

# parse topics
topiclist <- which(!is.na(cdat$topic))
cdat$Topics[topiclist] <- paste0("<ul><li>", cdat$topic[topiclist], "</li></ul>")
cdat$Topics[topiclist] <- gsub("(+.)\\*", "</li><li>", cdat$Topics[topiclist])

# parse notes
#notelist <- which(!is.na(cdat$notes))
#cdat$Materials[notelist] <- paste0("<ul><li>", cdat$notes[notelist], "</li></ul>")
#cdat$Materials[notelist] <- gsub("(+.)\\*", "</li><li>", cdat$Materials[notelist])

# parse Prepare
plist <- which(!is.na(cdat$before))
cdat$Prepare[plist] <- paste0("<ul><li>", cdat$before[plist], "</li></ul>")
cdat$Prepare[plist] <- gsub("(+.)\\*", "</li><li>", cdat$Prepare[plist])

# parse in class
dolist <- which(!is.na(cdat$during))
cdat$Together[dolist] <- paste0("<ul><li>", cdat$during[dolist], "</li></ul>")
cdat$Together[dolist] <- gsub("(+.)\\*", "</li><li>", cdat$Together[dolist])

# parse hw
hwlist <- which(!is.na(cdat$after))
cdat$HW[hwlist] <- paste0("<ul><li>", cdat$after[hwlist], "</li></ul>")
cdat$HW[hwlist] <- gsub("(+.)\\*", "</li><li>", cdat$HW[hwlist])
```

```{r results='asis', echo=FALSE, eval=TRUE}
out <- select(cdat, Notes, Date, Topics, Prepare, Together, HW )

knitr::kable(out, align="l", escape=FALSE) %>% 
  kable_styling(bootstrap_options = c("hover", "striped", "responsive", "bordered")) %>% 
  column_spec(1, width="8%") %>% column_spec(2, width="1%") %>%
  column_spec(3, width="20%") %>% column_spec(4, width="25%") %>%
  column_spec(5, width="10%") %>% column_spec(6, width="30%")
```

```{r results='asis', echo=FALSE, eval=FALSE}
out <- select(cdat, Notes, Date, Topics, HW )

knitr::kable(out, align="l", escape=FALSE) %>% 
  kable_styling(bootstrap_options = c("hover", "striped", "responsive", "bordered")) %>% 
  column_spec(1, width="5%") %>% column_spec(2, width="1%") %>%
  column_spec(3, width="30%") %>% column_spec(4, width="40%")
```


