---
title: 'Week 2: 8/28 - 9/3'
date: "Last Updated `r Sys.time()`"
output:
  html_document:
    highlight: tango
    theme: cerulean
    toc: yes
    toc_float: yes
css: css/customh5.css
---

```{r,echo=FALSE, warning=FALSE, message=FALSE}
library(knitr)
#library(rmarkdown)
opts_chunk$set(warning=FALSE, message=FALSE) 
```


# Monday: Data Archtecture
Goals: 

* Identify the different data types
* Learn how data is stored and tips on data entry to make analysis easier. 


## Prepare 

* Watch PDS [Video 2](http://passiondrivenstatistics.com/2015/06/02/chapter-2-draft-version/)
* Read Course Notes (CN) Section 2.1 and Open Intro Textbook (OI) Section 1.2. 
* Write answers to questions and examples in the CN. 
* Download the [medical records PDF](https://norcalbiostat.netlify.com/data/raw_data/) data from the raw data page. 


## In class
* RAT on Data Types
* Discuss answers to questions in CN 2.1
* Medical records assignment [[Instructions]](docs/MedRecords.html)

##### Assignments
* PS 2.2 (BBL Quiz)
* Data Camp (2 lessons): Open Intro - Intro to R, and Intro to Data
    - Complete both corresponding BBL quizzes 


----

# Wednesday:
Goals: 

* Import the Add Health data  into R
* Start to narrow down your research area of interest to some specific questions. 
* Start building your own personal codebook.

## Prepare
* Start a new `projects` folder in your `MATH315` folder. 
    - Download the AddHealth data set into a `data` subfolder 
    - So your data should be in `MATH315/projects/data`
* Start a new R Markdown file
    - Delete the template material _below the first code chunk_.
    - Update the author list to have both team members names
    - Save it as **AddHealth_DM.Rmd** into your `projects/code` folder. 
    - Knit to make sure there are no errors. 

## In class
* Learn how to read and create a codebook
* Import the Add Health data into R. 
    - We will be continually working in this file in the next few weeks. 
    - You and your analysis buddy will have to work out a way to ensure that both of you have the exact same data management code at all times. 
  

##### Assignments
* Research question / personal codebook assignment instructions as [[HTML]](hw/personal_codebook_assignment.html) and [[PDF]](hw/personal_codebook_assignment.pdf) 


----

# Friday:
Goals: 

* Verbalize your research topic or area of interest
* Learn how to start a literature review to refine and support your research topic

## Prepare
* Read [How to read a journal article](docs/How to Read a Journal Article.pdf)
* Read notes on conducting a literature review. Available as [[HTML]](docs/lec_lit_review.html) or [[PDF]](lec_lit_review.pdf).
* Watch PDS [Video 4](http://passiondrivenstatistics.com/2015/09/16/chapter-04/)

## In class
* Share your research topic with the class
* Search primary sources, take notes of articles to further look into. 

## Additional Resources
* [Help using the library](http://library.csuchico.edu/help)
* [Connecting to Meriam library from off campus](http://library.csuchico.edu/connecting-off-campus)


##### Assignments
* Citation assignment instructions as [[HTML]](hw/citation_assignment.html) and [[PDF]](hw/citation_assignment.pdf)
    - Write your responses in this[[RMD Template]](hw/citation_assignment_template.Rmd)
    - [Example assignment](docs/Citation Assignment Example.pdf)
    
    
    
