---
title: 'Week 3: 9/4 - 9/10'
date: "Last Updated `r Sys.time()`"
output:
  html_document:
    highlight: tango
    theme: cerulean
    toc: yes
    toc_float: yes
css: css/customh5.css
---


# Wednesday: Describing Continuous Data
Goals: 

* Learn how to describe continuous data correctly using graphics, summary statistics and paragraphs. 

## Prepare
* Read OI 1.6.2, 1.6.6
* Read CN 2.2

## In class
* RAT on CN 2.2, 2.3 (Univariate descriptions)
* Discuss answers to questions in CN 2.2

##### Assignments
* PS 2.4 Calculating summary statistics 
* PS 2.5 Interpreting univariate numerical distributions 
* Data Camp: Intro to ggplot & corresponding BBL Quiz. 

----

# Friday: Describing Categorical Data
Goals: 

* Learn how to describe continuous data correctly using graphics, summary statistics and paragraphs. 


## Prepare
* Read OI 1.7
* Read CN 2.3 - prepare answers
* Watch [PDS Video 6](http://passiondrivenstatistics.com/2015/12/18/r-chapter-6/) (30 min - 1hr)
    - It is suggested that you follow along with the code in this video by installing the `descr` package and downloading the NESARC data from [[this link]](https://drive.google.com/file/d/0B2-FPH8JVeuec29KQk5faENIMUk/view?usp=sharing), and the codebook from [[this link]](https://drive.google.com/open?id=0B2-FPH8JVeueY2c2WlgzcngwRlE). This is one of those things that will help you to achieve an "A" in this class. Not by points, but by putting effort into learning and practicing.
        - `install.packages("descr")`

## In class
* Discuss answers to questions in CN 2.3


##### Assignments
* PS 2.7 Interpreting univariate categorical distributions 
* Review your personal codebook. Answer the [[following]](hw/dm_assignment_prep.html) preparation questions directly in the [[RMD Template]](hw/dm_assignment_prep.Rmd). Upload the knitted WORD or PDF by the due date.  

##### IT IS HIGHLY ADVISED YOU LOOK AHEAD TO NEXT WEEK. 
We are starting data management which is a difficult coding topic. 
Your best chance of success with minimal strife is to follow along with the coding shown in PDS Video 7, replicate what they do in the video on your computer, and understand what the code means that you are writing. 

Some of these techniques I will show you on how to clean data take a different approach than what you will see in the PDS Video 7. That is fine! There are many different ways to approach and solve a problem. Being exposed to multiple ways of how to do things may seem confusing, but not everyone thinks the same. Some approaches may work better for some than for others. As you grow in being a scientist in charge of your own data you will find your own style of coding. 



