---
title: 'Week 4: 9/11 - 9/17'
date: "Last Updated `r Sys.time()`"
output:
  html_document:
    highlight: tango
    theme: cerulean
    toc: yes
    toc_float: yes
css: css/customh5.css
---


# Monday: Data Management
Goals: 

* Understand why data preparation takes the majority of your time, but is crucially important. 
* Learn how to identify mistakes and missing data in data using tables and summaries
* Learn how to correct certain mistakes
* Learn how to recode variables into new ones


## Prepare 
* Watch PDS [Video 7](http://passiondrivenstatistics.com/2016/01/08/r-chapter-7/)
    - Follow along with the NESARC data. Links to download the data can be found in [[Week 3]](https://norcalbiostat.github.io/MATH315/wk03.html)
* Review the notes on [[doing data management]](https://norcalbiostat.netlify.com/lec/doing-dm)
    - Download this `dm_depress` [[RMD]](docs/dm_depress.Rmd) file into your `MATH315/code` folder. 
    - Open the depression data set [[codebook]](https://norcalbiostat.netlify.com/data/DepressCodebook.txt) for use during class. 

## In class
* RAT on data management
* Go through the data cleaning code, and answer questions about what we're doing and why.
    

## Additional Resources
* R Cookbook http://www.cookbook-r.com/
* QUick-R http://www.statmethods.net/


##### Assignments
* Submit your `dm_addhealth.Rmd` code file to Blackboard by the due date. 
    - Make sure it works on both people's computers before you submit. 
    - I will download this file and run it on my machine. If it works it will be graded for correctness. 
    - I do not expect you to have all of your variables cleaned and transformed by this date.
        * But I do expect you to have at least a few variables done. 


# Wednesday: Data Viz
Goals: 

* Learn how to create univariate data graphics and summary statistics in R
* Describe the distribution of a single variable in sentence form using summary statistics and pointing out specific features of the graphics as evidence to support your interpretation. 


## Prepare
* Watch [[PDS Video 8]](http://passiondrivenstatistics.com/2016/01/20/r-chapter-8/). 
    - As before, following along and replicating the code in the video is highly recommended. 
* Start a new RMD file. Replicate all code to create **univariate graphics** from the [Data viz tutorial website](https://norcalbiostat.github.io/MATH130/materials/day56-data-viz.html). 


## In class
* Project overview to date
* Discuss graphing assignment
* Answer questions on how/why we produce what graphings
* 2:1 meetings regarding RQ & Variable selection
  - Reminder that using language verbatim from the example assignments in your assignments is considered plagerism. 
* Work on graphing assignment

##### Assignments
* Univariate graphing assigment. [[HTML instructions]](hw/univ_graphing.html)
    - [Example assignment](docs/Univariate Graphing Assignment Examples.pdf)


----

# Friday: Research Outline
Goals: 

* Describe the difference between a research plan and an empirical paper.
* Finish the two previous assignments on data management and graphing. 

## Prepare

* Read: Writing about empirical research [[HTML]](https://norcalbiostat.netlify.com/lec/lec_writing_em/)

## In class

* Introduce research plan outline assignment. 
* Finish the two previous assignments on data management and graphing. 


##### Assignments
* Research plan outline [[HTML instructions]](hw/research_plan_outline.html)

