---
title: 'Week 6: 9/25 - 10/1'
date: "Last Updated `r Sys.time()`"
output:
  html_document:
    highlight: tango
    theme: cerulean
    toc: yes
    toc_float: yes
css: css/customh5.css
---

```{r,echo=FALSE, warning=FALSE, message=FALSE}
library(knitr)
#library(rmarkdown)
opts_chunk$set(warning=FALSE, message=FALSE) 
```


# Monday: Writing
Goals: 

* Describe the differences between writing a research proposal and and empirical paper. 

## Prepare 
* Read Writing about Empirical Research [[HTML]](http://www.norcalbiostat.com/lec/lec_writing_em.html)

## In class
* Discuss the [Research Plan Outline](hw/research_plan_outline.html) assignment. 


##### Assignments
* Research plan outline 

----


# Wednesday: Exam 1

## Prepare
* Review the [sample exam](docs/Sample_Exam_1.pdf)
* Go through your course reader and make sure you've filled out all the questions and examples. 

##### Assigments
* Error Assessment (Optional)
    - Take your returned exam and go over it carefully. 
    - Print out [this form](docs/error_assessment.pdf) and use it to understand what types of mistakes you are making. 
    - Correct your exam on a new piece of paper. 
    - Go over your returned exam with a tutor, with a specific eye towards what _type_ of mistakes you made. **Do not go to a tutor until you have made your own corrections**
    - Have the tutor sign off on your visit. 

You can earn up to half credit of the total missed points back by returning the form, corrected work and exam back to me by 10/6. 


---- 

# Friday: Probability
Goals: 

* Give an example of a random variable
* Draw a normal distribution given the mean and variance
* Use R to find a probability under a normal model
* Be able to apply the empirical rule to estimate the proportion of data lying between two values assuming a normal model. 


## Prepare
* Watch two videos from our textbook authors on the [[Normal Distribution]](https://www.youtube.com/watch?list=PLkIselvEzpM6V9h55s0l9Kzivih9BUWeW&v=S_p5D-YXLS4) and [[Assessing Normality]](https://www.youtube.com/watch?v=smJBsZ4YQZw&index=2&list=PLkIselvEzpM6V9h55s0l9Kzivih9BUWeW)
* Read Chapter 3 of the course notes and fill out as much of the examples and blank spots in the readers as possible. Come to class prepared with questions. 

## In class
* Work through Chapter 3 in the course notes on probability and the normal distribution. 


##### Assignments (Both BBLearn quizzes)
* PS 3.1 Using the Normal Model
* PS 3.2 Probability Densities and Assessing Normality

Check your work? Use the ShinyEd Distribution Calculator: http://www2.stat.duke.edu/~mc301/shinyed/ 
