---
title: 'Week 9: 10/6 - 10/22'
date: "Last Updated `r Sys.time()`"
output:
  html_document:
    highlight: tango
    theme: cerulean
    toc: yes
    toc_float: yes
css: css/customh5.css
---

```{r,echo=FALSE, warning=FALSE, message=FALSE}
library(knitr)
#library(rmarkdown)
opts_chunk$set(warning=FALSE, message=FALSE) 
```


# Monday: 2 Samp T-test for diff

Goals: 

* Conduct a two-sample T-test on your Add Health variables. 

## Prepare 
* Read Course Notes section 6.2 (means) and 6.3 (proportions)
* Watch videos associated with corresponding Sections from Open Intro (5.3 for means), (6.2 for proportions)
    - Go to the PDF version of the OI book. 
    - Click on the table of contents for Section 5.3: Difference of Two Means
    - The Video camera icon takes you to a short video. 
    - The letter icon takes you to a set of Google Slides
    - Repeat for section 6.2: Difference of Two Proportions
* Read over the [Bivariate Inference](hw/Bivariate_Inference.html) assignment. 
    - Download this [template](hw/bivariate_Inference_template.Rmd) to your `Projects` folder. 
     - Name it `team_name_bivariate.Rmd`

## In class

* Conduct a Two-sample T-test on your add health data. Write up your results as question 1 in the Bivariate analysis homework assignment. 
    - Knit and upload your document to the shared [[Google Drive Bivariate Inference]](https://drive.google.com/drive/folders/0B83Z8_sNw3KPWGQxU1FsNm1DcG8?usp=sharing). No it's not due for grading yet, but it's important to contribute to our learning community. 

##### Assignments
* [Bivariate Inference](hw/Bivariate_Inference.html) Assignment.

    
----

# Wednesday: ANOVA

Goals: 

* Explain why ANOVA >> multiple Two-Sample T-tests for overall family-wise Type I error rates. 
* Conduct an ANOVA on your add health data.

## Prepare
* Read the Course Notes Section 6.4 (RAT MATERIAL)
* Watch [PDS video 11](http://passiondrivenstatistics.com/2016/05/11/r-chapter-11/)


## In class

* Conduct an ANOVA test on your add health data. Write up your results as question 2 in the Bivariate analysis homework assignment.
    - Knit and upload your document to the shared [[Google Drive Bivariate Inference]](https://drive.google.com/drive/folders/0B83Z8_sNw3KPWGQxU1FsNm1DcG8?usp=sharing). 

----

# Friday: $\chi^{2}$ test

## Goals

* Use a $\chi^{2}$ test to make inference on a bivaraite categorical relationship. 


## Prepare
* Watch [[PDS video 12]](http://passiondrivenstatistics.com/2016/06/29/r-chapter-12/) 

## In Class

* Conduct a $\chi^2$ test on your add health data. Write up your results as question 3 in the Bivariate analysis homework assignment. 
    - Knit and upload your document to the shared [[Google Drive Bivariate Inference]](https://drive.google.com/drive/folders/0B83Z8_sNw3KPWGQxU1FsNm1DcG8?usp=sharing). 
