---
title: 'Week 11: 10/30 - 11/5'
date: "Last Updated `r Sys.time()`"
output:
  html_document:
    highlight: tango
    theme: cerulean
    toc: yes
    toc_float: yes
css: css/customh5.css
---

```{r,echo=FALSE, warning=FALSE, message=FALSE}
library(knitr)
#library(rmarkdown)
opts_chunk$set(warning=FALSE, message=FALSE) 
```


# Monday: Moderation 

Goals: 

* Demonstrate how to determine if a third variable alters the relationship between your response and explanatory varibles. 


## Prepare 

* Watch Passion Driven Stats [Video 14](http://passiondrivenstatistics.com/2016/08/20/r-chapter-14/)

## In class
 
* Short lecture
* Work on Moderation assignment

##### Assignments

* [Moderation Assignment](hw/Moderation.html)
    - Assignment [[template RMD]](hw/Moderation_template.Rmd) file. 
    - Completed Assignments for review [[here]](https://drive.google.com/drive/folders/0B83Z8_sNw3KPU3dsamgwOWVHVzg?usp=sharing)
    
----


# Wednesday: Study Design

Goals: 

* Explain the difference between an Experiment and an Observational study
* Identify which can be used to make causal claims
* Explain the difference between a moderator, mediator, confounder and covariate


## Prepare 
* Review Course notes Chapter 1. Fill out questions along the way in the notebook. 


## In class
* Lecture through the study design notes, answer questions along the way.  


----

# Friday: Multivariable Regression

Goals: 

* Fit and interpret a multivariable regression model
* Identify if a variable is a confounder

## Prepare
* Watch PDS [video 17](http://passiondrivenstatistics.com/2016/10/06/r-chapter-17/) 
* Read Course Notes, Chapter 8.1-8.4
* Read Open Intro, Chapter 8.1-8.3

## In class
* Student Evaluations of Teaching (SETs) (20 min)
* Short lecture on fitting and interpreting regression models


##### Assignments

* [Regression Assignment](hw/regression_assignment.html)
    - Assignment [[template RMD]](hw/regression_template.Rmd) file. 
    - Completed Assignments for sharing  [[here]](https://drive.google.com/drive/folders/0B83Z8_sNw3KPcFBabzNpNHFOdFU?usp=sharing)
  
