---
title: 'Week 12 11/6 - 11/12'
date: "Last Updated `r Sys.time()`"
output:
  html_document:
    highlight: tango
    theme: cerulean
    toc: yes
    toc_float: yes
css: css/customh5.css
---

```{r,echo=FALSE, warning=FALSE, message=FALSE}
library(knitr)
#library(rmarkdown)
opts_chunk$set(warning=FALSE, message=FALSE) 
```


# Monday: Categorical Predictors 

Goals: 

* Fit a multiple regression model using a categorical predictor by means of several indicator variables, and interpret the results. 


## Prepare 

* Read Course Notes Ch 8.5
* Additional [[lecture notes]](https://norcalbiostat.github.io/MATH615/docs/lec07_MLR.html#categorical_predictors) on categorical predictors from MATH 615. 

## In class
 
* Brief lecture / answer questions about interpreting indicator variables. 
* Work on [Regression Assignment](hw/Regression_Assignment.html)

---

# Wednesday: Open work time

Goals: 

* Work on the Regression Assignment
* Work on poster prep stage III


##### Necessary Poster Updates

* Sample characteristics - this is from YOUR analysis sample. 
* Trim down # of RQ's. work on answering 1 or 2 fully. 
* Check for potential moderators, confounders.
* Check your grade from poster prep I
* Review any suggestions that are pending (from me or others) in your slides, or in the returned assignment. 

----

# Friday: No Class
