---
title: 'Week 13 11/3 - 11/17'
date: "Last Updated `r Sys.time()`"
output:
  html_document:
    highlight: tango
    theme: cerulean
    toc: yes
    toc_float: yes
css: css/customh5.css
---

```{r,echo=FALSE, warning=FALSE, message=FALSE}
library(knitr)
#library(rmarkdown)
opts_chunk$set(warning=FALSE, message=FALSE) 
```


# Monday: Logistic Regression

Goals: 

* Learn how to fit a model to a binary outcome
* Interpret logistic regression coefficients as Odds Ratios

## Prepare 
* Read Open Intro section 8.4
* Review last part of PDS Video 17
* Review the notes on Logistic Regression [[HTML]](docs/lec08_LogReg.html) [[PDF]](docs/lec08_LogReg.pdf)

## In class
* Primarily Lecture and discussion

##### Assignments
* Work on [Regression Assignment](hw/Regression_Assignment.html)


---

# Wednesday: Model building

### Goals: 

* Compare the fit between two linear models
* Use the Wald Test to test if a categorical variable is associated with the outcome

### Prepare: 
* Install the `survey` package. 
* Read Open Intro 8.2: Model Selection
* Review the notes on Variable Selection [[HTML]](docs/lec09_VarSelect.html) [[PDF]](docs/lec09_VarSelect.pdf)

## In class
* Short Lecture 

----

# Friday: Open work time


Goals: 

* Finish the Regression Assignment
* Finish poster prep stage III

In class: 

* Check for potential moderators, confounders.
* Check your grade from poster prep I & II
* Review any suggestions that are pending (from me or others) in your slides, or in the returned assignment. 

