---
title: "Research Plan Outline"
output:
  html_document:
    highlight: tango
    theme: cerulean
css: ../css/customh5.css
---

Your research plan is an important component of your final research project. This assignment is worth about 10% of your project grade since it acts as the basis for your final poster. You will spend the next two weeks writing your research plan, using the outline template below to help organize your writing. You also should use the model sections found in the reading [writing about empirical research](https://norcalbiostat.netlify.com/lec/lec_writing_em/) to help guide your writing style. 

> This is not a trivial assignment that should be attempted the night before it's due. 

You should start this assignment immediately. That means work on it directly after the exam. Return to it every few days until complete. Reread it and edit for clarity and readability before you turn it in. Run Spellcheck!

This assignment is to be submitted as a WORD or PDF document through Blackboard.


# Title
Using what you know now about your project and the model title in the reading, develop a working title fully knowing it is going to probably change. 

* Your title should summarize the main idea of your research question.
* Must include the variables under investigation.
* Must be fully explanatory when standing alone. 
* Include the terms “association between” or “relationship between” in your title to join your variables of interest.  
 

# Introduction 
Write an opening statement or questions to grab the reader. This statement introduces your topic and gives your rationale for the study. This is going to be a working opening statement that will develop more as you go.	
    
* Create an outline of topics you know you will need to discuss to be able to identify major trends in the literature and emphasize major findings. 
* As you have been reading you should have been seeing some of the same topics/findings/themes reappearing, these would be good topics to include.

# Methods
* Name the data set and discuss at least 3 key features of the sample or way data were collected.
    - The three key features should have supporting data.
* Create one outline point for each of your variables directly used to answer your research question. 
    - What are they and how were they measured?
    - Describe any data management you might have done on these variables. Specifically talk about any collapsing of variable categories, dichotomizing, and removing outliers. Do not talk about missing data recoding (i.e. 96 and 98 to missing)
 
# Predicted Results
* At least 2 outline points stating how you think your variables will be related/associated. 
    - Look back to your research question and think about “answering” it.

