---
title: "Syllabus for Applied Statistical Methods I"
author: "Dr. Robin Donatello"
date: "MATH 315, Fall 2017"
output:
  html_document: default
  pdf_document: default
geometry: margin=0.75in
urlcolor: blue
---

# Logistics
* **Instructor:** Dr. Robin Donatello  
* **Office Location:** Holt 202  
* **Phone Number:** 898-5767  
* **E-mail:** rdonatello at csuchico dot edu   
* **website:** https://norcalbiostat.github.io/MATH315/ 
* **Prerequisites:** Basic computer literacy. Recent statistics course such as Math 105. 
* **Meeting Days and Times** 
    - Section 02 MWF 10-11 noon HOLT 257
    - Section 01 MWF 12-1 pm HOLT 277

    
You can download the Syllabus in PDF form by clicking [this link](syllabus_f17.pdf).


## Learning Outcomes

By the end of the semester students will be able to 

* Develop a testable research question. 
* Create and Understand how to use a codebook to identify data relevant to that question. 
* Process, screen, recode, transform, and clean data.
* Describe data using visualizations and words. 
* Select and carry out an appropriate statistical analysis.
* Explain study results and limitations to a non-technical audience. 
* Understand and implement a reproducible research pipeline. 
* Become a data nerd (Optional, but recommended).


## Required Materials

* **Textbook**: Open Intro Statistics https://www.openintro.org/stat/textbook.php?stat_book=os 
* **Course Notes**: Purchase from Chico Packet Pro for $18. You will write directly into this inside and outside of class. 
    - Chico Packet Pro store will be open from: 
    - Friday, August 18 - Wednesday, September 6
    - Mon-Thu 10-6, Fri 10-5, Sat 8/19 + 8/26 from 10-2
    - 230 Salem Street and our entrance is on the city parking lot side of the building. We accept cash, debit and credit cards.
    - Online at https://squareup.com/store/chico-packet-pro/item/math-course-notes-prof-donatello
    - A color [PDF](RAD_course_notes.pdf) version available as supplementary material. The hard copy still must be purchased. We will be working directly out of it during class. 
* **Reliable Laptop with internet connectivity**: Required to bring every day. Contact me if this poses a problem or concern for you. 
* **Headphones:** In case you forget to watch a required video before class you may be asked to do so in class. 
* **Computer Software:** All required software is free. Instructions on how to download and install can be found at this link: https://norcalbiostat.netlify.com/post/software-overview/
* **Blackboard Learn Use:** I will use Blackboard learn for
    - Regular Announcements (which will also get emailed to your campus email)
    - Submitting and returning assignments
    - Due Dates
    - Grades
* **Accounts** [Chico R Users Google Group](https://groups.google.com/forum/#!forum/chico-rug) 
    - The Data Camp sign up link will be emailed to you directly before Day 1. You must use this link to join our online classroom. 

\newpage

## Coursework

There are a variety types of assignments that I use to help you learn, and to assess how well you have
learned the material and can synthesize information. These categories are listed below, somewhat 
ordered in roughly how prompt the feedback is (Top:immediate, Bottom: could take over a week)

1. **Participation**: I will call on people to answer questions from the course notes. 
    - Having an answer ready to go (correct or not) will earn you participation for that day. 
    - I won't get to everyone every day, but count on being called upon at least 1x/week. 
2. **BBLearn (BBL)**: These are a random set of questions from a pool of questions.
    - Assigned as specific problem sets from the course notes. 
    - Typically conceptual, sometimes computational.
    - Designed to reinforce concepts we covered in class in a non-threatening way. 
    - You have unlimited attempts to earn the score you desire. 
    - Late submissions are accepted until EOD of the day before the upcoming exam. (Can be an exam study tool).
3. **Data Camp (DC)**: We will primarily use Data Camp to learn R outside of class. 
    - You must be logged in to the Data Camp classroom to get access to the lessons. 
    - You must use the link emailed to you to join this classroom. 
    - There will be a corresponding BBLearn learn quiz associated with each lesson. 
    - You will have multiple (but not unlimited) attempts at these quizzes. 
    - Questions can be conceptual, interpreting results, and asking you to write code to demonstrate a task that was covered in the lesson. 
4. **Learning**: These types of assignments are all designed to help you become aware of how you learn and how you can become a more active learner. 
    - Learning assignments take the form of readiness assurance tests (RAT), Exam error assessments and meta-cognition assessments and reading. 
5. **Written**: Written assignments are methods to demonstrate you have learned the material covered in class that day or that week. 
    - These can be worksheets or labs that we do together as a class. 
    - There are additional problem sets in the course notes. 
        - I have decided not to collect these problems this semester, but all the solutions are freely available in my office at any time. 
        - Doing these problem sets will give you the additional practice and reinforcement of concepts and skills that could be the difference between getting an A in the course, and a C. 
6. **Exams:** There will be 3 exams. 
    - An Error Analysis can be conducted on Exam 1 and 2 to earn back up to half the credit missed. 
    - This is where you get back your exam, fix your mistakes, and explain your corrections verbally to either me or a tutor. 
7. **Project:** You will be working in pairs on a project throughout the term. 
    - There will be several assignments throughout the semester geared towards progressing your analysis project. 
    - You will present your work as a poster at the end of the semester. 
  

**Late work:** 

* Unless otherwise specified, you have roughly a week to do each assignment. 
    - Recall the due dates can be found in the BBL Calendar, or on the main schedule page. 
* **Late work is not accepted** (with the exception of BBL quizzes)
 
## Extra Credit

Yes I am putting EC in the syllabus. 

* I do not answer programming/debugging questions via email.  
* All questions **not pertaining to class logistics or assignments** and specifically about programming are to be posted to the [Chico R Users Group](https://groups.google.com/forum/#!forum/chico-rug). 
    - Contributing answers to this forum can earn you some Ec. 
* Being public about your questions  
    - Helps you ask better questions  
    - Reminds you that you are not alone in your struggle  
    - Gives you a place to start to search for an answer to your question  


## Grading

* Your final grade will be a straight sum of points earned and will be displayed as a running total in Blackboard Learn.  
* The approximate contributions per category are: In class participation, BBLearn, Reading, Learning and R are combined worth about 25\%, Written assignments 10\%, Exams 25\%, and the Project 30\%.   
* I use a standard grade cutoff of 100-90\%: A, 89-80\%: B, 79-70\%: C, 69-60\%: D, 0-59\%: F Plusses and minuses will be as displayed on Blackboard Learn. 

# Topic Overview

* Data Collection and recording
* Preparing data for analysis
* Data Visualization
* Foundations for Inference: Random variables, Parameters vs. Statistic, Confidence Intervals, Hypothesis Testing
* Inference for a single sample (t-tests, $\chi^{2}$ tests)
* Inference comparing multiple samples (t-tests, ANOVA, $\chi^{2}$ tests)
* Linear regression analysis (Simple and Multiple, Categorical predictors and contrasts)
* Logistic Regression analysis


## Adding and Dropping the course
The last day to drop or add a course is 9/15/17. After this date, withdraws will only be allowed for serious and compelling reasons subject to department chair approval.

## Americans with Disabilities Act
If you need course adaptations or accommodations because of a disability or chronic illness,  or if you need to make special arrangements in case the building must be evacuated, please make an appointment with me as soon as possible, or see me during office hours. Please also contact Accessibility Resource Center (ARC) as they are the designated department responsible for approving and coordinating reasonable accommodations and services for students with disabilities. ARC will help you understand your rights and responsibilities under the Americans with Disabilities Act and provide you further assistance with requesting and arranging accommodations.

Accessibility Resource Center  
530-898-5959   
Student Services Center 170  
arcdept@csuchico.edu  




_Last updated: `r format(Sys.time(), "%a %b %d %Y %X")`_

